# Generated by Django 3.1.7 on 2021-02-24 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryName', models.CharField(max_length=64)),
                ('categoryDesc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=64)),
                ('phoneNum', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=64)),
                ('aboutMe', models.TextField()),
                ('aboutSession', models.TextField()),
                ('address', models.TextField()),
                ('offerName', models.CharField(max_length=64)),
                ('offerDesc', models.TextField()),
                ('offerPrice', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='photos/')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.category')),
            ],
        ),
    ]
