# Generated by Django 3.1.7 on 2021-02-24 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20210224_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(blank=True, default=None, upload_to='photos/media/'),
        ),
    ]
